# Generated by Django 4.2.1 on 2023-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('id',), 'verbose_name': 'user'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='access_levels',
            field=models.CharField(choices=[('admin', 'Admin'), ('authorized user', 'Authorized'), ('guest', 'Guest')], default='guest', max_length=50, verbose_name="user's role"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email already exists.'}, max_length=254, unique=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='second name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Such a user already exists.'}, max_length=150, unique=True, verbose_name='login'),
        ),
    ]
